accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path ('register/',views.user_register , name= 'user_register'),
    path ('login/',views.user_login , name= 'user_login'),
    path ("logout/",views.user_logout, name='user_logout'),
    path ("profile/",views.user_profile, name='user_profile'),
    path ("update/",views.user_update, name='user_update'),
    path ("addresses/",views.user_addresses, name='user_addresses'),
    path ("changepassowrd/",views.user_changepassword, name='user_changepassowrd'),
    path ("editaddress/<int:id>/",views.user_editaddress, name="user_editaddress"),# type: ignore
    path ("addaddress/",views.user_addaddress,name='user_addaddress'),# type: ignore
    path ('deleteaddress/<int:id>/',views.user_delete_address,name='user_delete_address'),
]
 

home/urls.py
#urls.py
from django.urls import path
from . import views

app_name = 'home' 

urlpatterns = [
    path ('' , views.home ,name= 'home'),
    path ('product/',views.product , name = 'product'),
    path ('productdetail/<int:id>/',views.productdetail, name = 'productdetail'),
    path ('category/<slug>/<int:id>',views.product, name = 'category'),
]
handler404 = 'myapp.views.custom_404_view'

website/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path ('admin/', admin.site.urls),
    path ('',include('home.urls' ,namespace = 'home')),
    path ('accounts/',include('accounts.urls',namespace= 'accounts'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save,post_delete,pre_save,pre_delete,m2m_changed
#from django.core.signals import request_finished , request_started
# Create your models here.

class Profile (models.Model):
    user = models.OneToOneField(User,on_delete = models.CASCADE) # on_delete = models.DO_NOTHING ,SET_NULL , ....
    phone = models.IntegerField(null=True ,blank=True)
    address = models.CharField(max_length=300,null=True ,blank=True)
    postalcode = models.IntegerField(null=True ,blank=True)

    def __str__(self):
        return self.user.username
def save_profile_user(sender ,**kwargs):
    if kwargs ['created'] : # create is boolean Ture or False
        user_profile = Profile(user = kwargs ['instance'])
        user_profile.save()
    else:
        pass

post_save.connect (sender= User ,receiver=save_profile_user)


class UserAddresses(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='addresses')
    title = models.CharField(max_length=50)  # مثلا "خانه"، "محل کار"
    city = models.CharField(max_length=100)
    street = models.CharField(max_length=200)
    postal_code = models.CharField(max_length=20, blank=True, null=True)
    is_Default = models.BooleanField(blank=True,null=True)
    # می‌توانی فیلدهای بیشتری مثل شماره واحد، توضیحات و ... اضافه کنی

    def __str__(self):
        return f"{self.profile} -{self.title} - {self.city}"

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile ,UserAddresses

error = {
    'min_length':'حداقل باید 5 کاراکتر داشته باشد',
    'required':'این فیلد اجباری است',
    'invalid':'ایمیل نامعتبر است',
}
class UserRegisterForm (forms.Form):
    Username = forms.CharField(error_messages=error, max_length = 50,min_length=5 )
    Email = forms.EmailField(error_messages=error)
    Firstname = forms.CharField(max_length=50)
    Lastname = forms.CharField (max_length=50)
    Password_1 = forms.CharField(max_length=50)
    Password_2 = forms.CharField(max_length=50)

    # def name is clean_field need to validate
    def clean_Username (self):
        user = self.cleaned_data ['Username']
        if User.objects.filter ( username = user).exists():
            raise forms.ValidationError ('این نام کاربری استفاده شده')
        return user
    
    def clean_Email (self):
        email = self.cleaned_data ['Email']
        if User.objects.filter (email = email).exists():
            raise forms.ValidationError ("این ایمیل تکراری است ")
        return email
    
    def clean_Password_2 (self): # must same feild like clean_field = clena_Lastname
        pass_1 = self.cleaned_data ['Password_1']
        pass_2 = self.cleaned_data ['Password_2']
        if pass_1 != pass_2:
            raise forms.ValidationError ('پسورد ها یکسان نیست')
        
        return pass_2

class UserLoginForm (forms.Form):
    user = forms.CharField()
    password = forms.CharField()


class UserUpdateForm (forms.ModelForm):

    class Meta:
        model = User
        fields = ['email','first_name','last_name']


class ProfileUpdateForm (forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['phone','address','postalcode']


class UserEditAddressForm (forms.ModelForm):

    class Meta:
        model = UserAddresses
        fields = ['title','city','street','postal_code','is_Default']

class UserAddAddressForm (forms.ModelForm):

    class Meta:
        model = UserAddresses
        fields = ['title','city','street','postal_code','is_Default']

accounts/views.py
from django.shortcuts import render ,redirect
from .forms import UserRegisterForm ,UserLoginForm ,UserUpdateForm ,ProfileUpdateForm ,UserEditAddressForm,UserAddAddressForm
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth import authenticate ,login ,logout
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required

class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['old_password'].label = "کلمه عبور فعلی"
        self.fields['new_password1'].label = "کلمه عبور جدید"
        self.fields['new_password2'].label = "تکرار کلمه عبور جدید"

        # اضافه کردن placeholder فارسی
        self.fields['old_password'].widget.attrs.update({'placeholder': 'کلمه عبور فعلی را وارد کنید'})
        self.fields['new_password1'].widget.attrs.update({'placeholder': 'کلمه عبور جدید را وارد کنید'})
        self.fields['new_password2'].widget.attrs.update({'placeholder': 'کلمه عبور جدید را دوباره وارد کنید'})

# Create your views here.

def user_register (request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user =User.objects.create_user(username = data['Username'] ,
                                     email= data['Email'] ,
                                     first_name = data['Firstname'] ,
                                     last_name = data ['Lastname'], 
                                     password=data ['Password_1'])
            user.save()
            return redirect ('home:home') # redirect ('appname : utl name from utls.py = 'home'')
    else:
        form = UserRegisterForm()
    context = {'form':form}
    return render (request , 'accounts/register.html',context)

def user_login (request):

    if request.method == 'POST':

        form = UserLoginForm(request.POST) # create An example where the user has entered information

        if form.is_valid():

            data = form.cleaned_data

            try:

                user = authenticate(request ,username = User.objects.get(email= data ['user']),password = data ['password'])

            except:

                user = authenticate(request ,username = data ['user'],password = data ['password'])

            if user is not None :

                login(request,user)
                messages.success(request,'با موفقیت وارد شدید.','success')
                return redirect ('home:home')
            
            else:

                messages.success(request,'نام کاربر یا رمز عبور اشتباه است','danger')
                redirect ('accounts:user_login')

    else:

        form = UserLoginForm()

    context = {'form':form}
    return render(request , 'accounts/login.html',context)    
    
def user_logout (request):

    logout(request)
    messages.success(request,'با موفقیت خارج شدید.','info')
    return redirect ('home:home')   

@login_required(login_url="accounts:user_login")
def user_profile (request):

    profile = Profile.objects.get(user_id = request.user.id)
    return render (request ,'accounts/profile.html',{'profile':profile})

@login_required(login_url="accounts:user_login")
def user_update (request):
    if request.method == "POST":
        user_form = UserUpdateForm(request.POST,instance=request.user)
        profile_form = ProfileUpdateForm(request.POST,instance=request.user.profile)
        if user_form and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request,'به روزرسانی با موفقت انجام شد','success')
            return redirect ('accounts:user_profile')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)
    context = {'user_form':user_form , 'profile_form':profile_form}
    

    return render (request , "accounts/update.html",context)




def user_addresses(request):
    # گرفتن پروفایل کاربر لاگین شده
    profile = request.user.profile
    
    # گرفتن همه آدرس‌های مرتبط با پروفایل
    addresses = profile.addresses.all()
    
    context = {
        "addresses": addresses
    }
    return render(request, "accounts/addresses.html", context)

def user_changepassword (request):

    if request.method == "POST":
        form = CustomPasswordChangeForm (request.user,request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            messages.success (request ,"کلمه عبور ما موفقیت تغییر کرد",'success')
            return redirect ("accounts:user_profile")
        else:
            messages.error (request ,"کلمه عبور درست انتخاب نشده",'danger')
            return redirect ('accounts:user_changepassowrd')

    else:
        form = CustomPasswordChangeForm(request.user)
    
    return render (request ,"accounts/changepassword.html",{'form':form})



def user_addaddress(request):

    if request.method == "POST":
        form = UserAddAddressForm(request.POST)
        if form.is_valid():
            address = form.save(commit=False)
            address.profile = request.user.profile  # یا هر فیلدی که کاربر رو نگه می‌داره
            if address.is_Default:
                UserAddresses.objects.filter(profile = address.profile,is_Default = True).update(is_Default=False)  
            address.save()
            messages.success(request,'نشانی با موفقیت ذخیره شد','success')
            return redirect ('accounts:user_addresses')
    else:
        form = UserAddAddressForm()
        return render(request,'accounts/addaddress.html',{'form':form})
    


def user_editaddress(request , id):
    address = UserAddresses.objects.get(id=id)
    if request.method == "POST":
        addressform = UserEditAddressForm(request.POST,instance=address)
        if addressform.is_valid():
            edited_address = addressform.save(commit=False)
            if edited_address.is_Default:
            # همه‌ی آدرس‌های دیگر این پروفایل رو غیر پیش‌فرض کن 
                UserAddresses.objects.filter( profile=edited_address.profile,
                                              is_Default=True
                                             ).exclude(id=edited_address.id).update(is_Default=False)     
            edited_address.save()           
            messages.success(request,'نشانی با موفقیت ذخیره شد','success')
            return redirect ('accounts:user_addresses' )
    else:
        addressform = UserEditAddressForm(instance=address)
        
        return render(request,'accounts/editaddress.html' ,{'addressform':addressform})
    

def user_delete_address(request, id):
    UserAddresses.objects.filter(id=id).delete() 
    messages.success(request, 'نشانی با موفقیت حذف شد', 'success') 
    return redirect('accounts:user_addresses')

accounts/templates/accounts/addaddress.html
{% extends "main.html" %}
{% load widget_tweaks %}

{% block title %}نشانی جدید{% endblock title %}
{% include "sidebar.html" %}
{% block body %}
<main class="col-12 col-md-12 p-4">

<br>
<form action="" method="post" class="needs-validation" novalidate>
    {% csrf_token %}

        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card shadow-sm border-0">
                    <div class="card-header bg-primary text-white text-center">
                        <h4 class="mb-0">ویرایش حساب کاربری</h4>
                    </div>
                    <div class="card-body">
                        <div class="mb-3">
                            <h6 class="text-muted">عنوان:</h6>
                            {{ form.title|add_class:"form-control"|attr:"style:width:100" }}
                        </div>
                        <div class="mb-3">
                            <h6 class="text-muted">شهر :</h6>
                            {{ form.city|add_class:"form-control"|attr:"style:width:100%" }}
                        </div>                    
                        <div class="mb-3">
                            <h6 class="text-muted">نشانی:</h6>
                            {{ form.street|add_class:"form-control"|attr:"style:width:100%" }}
                        </div>
                            <div class="mb-3">
                            <h6 class="text-muted">کدپستی :</h6>
                            {{ form.postal_code|add_class:"form-control"|attr:"style:width:100%"  }}
                        </div>
                        <div>
                            <div class="mb-3">
                            <h6 class="text-muted">آدرس پیش فرض :</h6>
                            {{ form.is_Default|add_class:"form-control"|attr:"style:width:100%"}}
                        </div>
                        <button type="submit" class="btn btn-primary">ذخیره</button>
                    </div>
</form>

            </main>
    
    </div>

</div>
{% endblock body %}

accounts/templates/accounts/addresses.html
{% extends 'main.html' %}
{% load static %}
{% block title %} آدرس های من {% endblock title %}
{% block body %}

        <!-- محتوای اصلی -->
        <main class="class="col-12 col-md-12 p-4" style=" margin-right: 10px; margin-top: 10px; margin-left: 10px; margin-bottom: 10px;">

            <h4 class="mb-0">آدرس های من
            <a href="{% url 'accounts:user_addaddress' %}" class="btn btn-success" style="border-radius:50%; padding:3px;"> 
            <img src="{% static 'icons/Add.svg' %}" alt="Add" style="width:24px; height:24px;"> 
            </a></h4>
            <hr class="border border-danger">

                {% if addresses %}
                {% for add in addresses%}
                    <div class="row card" style ="margin:10px;padding:5px; {% if add.is_Default %}background-color: #dfffe7ff;{% endif %}">
                        <div class="col">
                        
                    
                        عنوان :{{ add.title }}<br>
                        شهر :{{add.city}}<br>
                        آدرس :{{add.street}}<br>
                        کدپستی :{{add.postalcode}}<br>
                            <a type="button" class="btn btn-info" href = "{% url "accounts:user_editaddress" add.id %}" >
                                <img src ="{% static 'icons/Edit.svg' %}">
                                
                            </a>
                            <a type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop" >
                                <img src ="{% static 'icons/Delete.svg' %}">
                            </a>
                        


<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel"></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        آیا این مسیر حذف شود
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">خیر</button>
        <a type="button" class="btn btn-danger" href = "{% url "accounts:user_delete_address" add.id %}" >
            بله
        </a>
      </div>
    </div>
  </div>
</div>









                        </div>
                    </div>
                
                {% endfor %}
                {% endif%}

        </main>
    
    </div>

</div>

{% endblock %}

accounts/templates/accounts/changepassword.html
{% extends "main.html" %}
{% load widget_tweaks %}

{% block title %}ویرایش کلمه عبور{% endblock title %}
{% include "sidebar.html" %}
{% block body %}
<main class="col-9 col-md-10 p-4">

<br>
<form action="" method="post" class="needs-validation" novalidate>
    {% csrf_token %}

        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card shadow-sm border-0">
                    <div class="card-header bg-primary text-white text-center">
                        <h4 class="mb-0">ویرایش کلمه عبور </h4>
                    </div>
                    <div class="card-body">
                        
                        
                        {{form.as_p}}
                        <button type = 'submit' class="btn btn-primary"> اعمال</button>
                        
                    </div>
</form>


</main>
</div>
</div>


{% endblock body%}

accounts/templates/accounts/editaddress.html
{% extends "main.html" %}
{% load widget_tweaks %}
{% block title %}ویرایش آدرس{% endblock title %}

{% block body %}
<main class="col-9 col-md-10 p-4">

<br>
<form action="" method="post" class="needs-validation" novalidate>
    {% csrf_token %}

        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card shadow-sm border-0">
                    <div class="card-header bg-primary text-white text-center">
                        <h4 class="mb-0">ویرایش آدرس </h4>
                    </div>
                    <div class="card-body">
                        <div class="mb-3">
                            <h6 class="text-muted">عنوان:</h6>
                            {{ addressform.title|add_class:"form-control"|attr:"style:width:100" }}
                        </div>
                        <div class="mb-3">
                            <h6 class="text-muted">شهر:</h6>
                            {{ addressform.city|add_class:"form-control"|attr:"style:width:100%" }}
                        </div>                    
                        <div class="mb-3">
                            <h6 class="text-muted">نشانی:</h6>
                            {{ addressform.street|add_class:"form-control"|attr:"style:width:100%" }}
                        </div>
                            <div class="mb-3">
                            <h6 class="text-muted">کدپستی :</h6>
                            {{ addressform.postal_code|add_class:"form-control"|attr:"style:width:100%"  }}
                        </div>
                        <div>
                            <div class="mb-3">
                            <h6 class="text-muted">آدرس پیش فرض :</h6>
                            {{ addressform.is_Default|add_class:"form-control"|attr:"style:width:100%"}}
                        </div>
                        <button type="submit" class="btn btn-primary">به‌روزرسانی</button>
                    </div>
</form>

            </main>
    
    </div>

</div>
{% endblock body %}

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="fa" dir = 'rtl'>
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <style>
        body {
            background: linear-gradient(to bottom, #315ad3, #66aaff);
            height: 100vh;
            margin: 0;
            display: flex; /* دو بخش کنار هم */
        }
        .half {
            flex: 1; /* هرکدام نصف عرض */
            display: flex;
            align-items: center;   /* وسط‌چین عمودی */
            justify-content: center; /* وسط‌چین افقی */
        }
        .card {
            width: 80%;
            max-width: 400px;
        }
    </style>
</head>
<body>

   <div class="half">
        <!-- بخش اول -->
        <div class="card shadow">
            <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_user" class="form-label">نام کاربری یا ایمیل</label>
                            <input type="text" name="user" id="id_user" class="form-control">
                        </div>
                        <div class="mb-3">
                            <label for="id_password" class="form-label">رمز عبور</label>
                            <input type="password" name="password" id="id_password" class="form-control">
                        </div>
                        <button type="submit" class="btn btn-success w-100">ورود</button>
                    </form>
    </div>
           </div>
        </div>
    </div>

    <div class="half">
        
        <!-- Replace src with your actual file path -->
        <img src ="{% static 'Images/Logo.png' %}"
        alt="Minimal fashion illustration of a man and woman"
        loading="lazy"
        width="450"
        height="450"
        style="max-width: 100%; height: auto; display: block; margin: 0 auto;" />

    </div>
{%include 'message.html'%}
</body>
</html>

accounts/templates/accounts/profile.html
{% extends "main.html" %}

{% block title %}حساب کاربری{% endblock title %}

{% block body %}
<main class="col-12 col-md-12 p-4">
<br>

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-sm border-0">
                <div class="card-header bg-primary text-white text-center">
                    <h4 class="mb-0">حساب کاربری</h4>
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        <h6 class="text-muted">نام کاربری:</h6>
                        <p class="fw-bold">{{ profile.user.username }}</p>
                    </div>
                    <div class="mb-3">
                        <h6 class="text-muted">نام :</h6>
                        <p class="fw-bold">{{ profile.user.first_name }}</p>
                    </div>                    
                    <div class="mb-3">
                        <h6 class="text-muted">نام خانوادگی:</h6>
                        <p class="fw-bold">{{ profile.user.last_name }}</p>
                    </div>
                        <div class="mb-3">
                        <h6 class="text-muted">ایمیل :</h6>
                        <p class="fw-bold">{{ profile.user.email }}</p>
                    </div>
                    <div>
                        <div class="mb-3">
                        <h6 class="text-muted">آدرس :</h6>
                        <p class="fw-bold">{{ profile.address }}</p>
                    </div>
                    <div>
                        <div class="mb-3">
                        <h6 class="text-muted">کدپستی :</h6>
                        <p class="fw-bold">{{ profile.postalcode }}</p>
                    </div>
                    <a type="button" class="btn btn-success" href = "{% url "accounts:user_update" %}" >بروز رسانی</a>
                    <a type="button" class="btn btn-secondary" href = "{% url "accounts:user_changepassowrd" %}" >تغییر کلمه عبور</a>
                </div>

            </div>
        </div>

    </div>

</main>
    
</div>

</div>
{% endblock body %}

accounts/templates/accounts/register.html
<!DOCTYPE html>
<html lang="fa" dir = 'rtl'>
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock  %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'header.css' %}">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <link rel = "stylesheet" href = "{% static 'accounts/css/register.css'%}" >

</head>


<h2 class="text-center">فرم ثبت نام</h2> <br>
<body>
<form method="post" novalidate>
    {% csrf_token %}
    
    <div class="form-group">
        <label for="id_Username">نام کاربری</label>
        <input type="text" name="Username" id="id_Username" class="form-control">
        {% if form.Username.errors %}
            <div class="error">{{ form.Username.errors }}</div>
        {% endif %}
    </div>
    
    <div class="form-group">
        <label for="id_Email">ایمیل</label>
        <input type="email" name="Email" id="id_Email" class="form-control">
        {% if form.Email.errors %}
            <div class="error">{{ form.Email.errors }}</div>
        {% endif %}
    </div>
    
    <div class="form-group">
        <label for="id_Firstname">نام</label>
        <input type="text" name="Firstname" id="id_Firstname" class="form-control">
        {% if form.Firstname.errors %}
            <div class="error">{{ form.Firstname.errors }}</div>
        {% endif %}
    </div>
    
    <div class="form-group">
        <label for="id_Lastname">نام خانوادگی</label>
        <input type="text" name="Lastname" id="id_Lastname" class="form-control">
        {% if form.Lastname.errors %}
            <div class="error">{{ form.Lastname.errors }}</div>
        {% endif %}
    </div>
    
    <div class="form-group">
        <label for="id_Password_1">رمز عبور</label>
        <input type="password" name="Password_1" id="id_Password_1" class="form-control">
        {% if form.Password_1.errors %}
            <div class="error">{{ form.Password_1.errors }}</div>
        {% endif %}
    </div>
    
    <div class="form-group">
        <label for="id_Password_2">تکرار رمز عبور</label>
        <input type="password" name="Password_2" id="id_Password_2" class="form-control">
        {% if form.Password_2.errors %}
            <div class="error">{{ form.Password_2.errors }}</div>
        {% endif %}
    </div>
    
    <button type="submit" class="btn btn-success">ثبت نام</button>
</form>

</body>
</html>

accounts/templates/accounts/update.html
{% extends "main.html" %}
{% load widget_tweaks %}

{% block title %}ویرایش حساب{% endblock title %}
{% include "sidebar.html" %}
{% block body %}
<main class="col-9 col-md-12 p-4">

<br>
<form action="" method="post" class="needs-validation" novalidate>
    {% csrf_token %}

        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card shadow-sm border-0">
                    <div class="card-header bg-primary text-white text-center">
                        <h4 class="mb-0">ویرایش حساب کاربری</h4>
                    </div>
                    <div class="card-body">
                        <div class="mb-3">
                            <h6 class="text-muted">نام:</h6>
                            {{ user_form.first_name|add_class:"form-control"|attr:"style:width:100" }}
                        </div>
                        <div class="mb-3">
                            <h6 class="text-muted">نام خانوادگی:</h6>
                            {{ user_form.last_name|add_class:"form-control"|attr:"style:width:100%" }}
                        </div>                    
                        <div class="mb-3">
                            <h6 class="text-muted">ایمیل:</h6>
                            {{ user_form.email|add_class:"form-control"|attr:"style:width:100%" }}
                        </div>
                            <div class="mb-3">
                            <h6 class="text-muted">آدرس :</h6>
                            {{ profile_form.address|add_class:"form-control"|attr:"style:width:100%"  }}
                        </div>
                        <div>
                            <div class="mb-3">
                            <h6 class="text-muted">کدپستی :</h6>
                            {{ profile_form.postalcode|add_class:"form-control"|attr:"style:width:100%"}}
                        </div>
                        <button type="submit" class="btn btn-primary">به‌روزرسانی</button>
                    </div>
</form>

            </main>
    
    </div>
</div>
{% endblock body %}