accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path ('register/',views.user_register , name= 'user_register'),
    path ('login/',views.user_login , name= 'user_login'),
    path ("logout/",views.user_logout, name='user_logout'),
    path ("profile/",views.user_profile, name='user_profile'),
    path ("update/",views.user_update, name='user_update'),
    path ("addresses/",views.user_addresses, name='user_addresses'),
    path ("changepassowrd/",views.user_changepassword, name='user_changepassowrd'),
    path ("editaddress/<int:id>/",views.user_editaddress, name="user_editaddress"),# type: ignore
    path ("addaddress/",views.user_addaddress,name='user_addaddress'),# type: ignore
    path ('deleteaddress/<int:id>/',views.user_delete_address,name='user_delete_address'),
]
 

home/urls.py
#urls.py
from django.urls import path
from . import views

app_name = 'home' 

urlpatterns = [
    path ('' , views.home ,name= 'home'),
    path ('product/',views.product , name = 'product'),
    path ('productdetail/<int:id>/',views.productdetail, name = 'productdetail'),
    path ('category/<slug>/<int:id>',views.product, name = 'category'),
]
handler404 = 'myapp.views.custom_404_view'

website/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path ('admin/', admin.site.urls),
    path ('',include('home.urls' ,namespace = 'home')),
    path ('accounts/',include('accounts.urls',namespace= 'accounts'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/main.html
<!DOCTYPE html>
<html lang="fa" dir = 'rtl'>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock title %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'custom-css/header.css' %}">

    <link rel="stylesheet" href="{% static 'custom-css/sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'categoryimage.css' %}">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'home/js/custom.js' %}"></script>
</head>
<body>
    {% include "navbar.html" %} 
    {% include "sidebar.html" %}
    {% block body %} {% endblock body %}
    {% include "message.html" %}
</body>
</html>

templates/message.html
  <style>
    .custom-alert {
        font-size: 14px;
        position: fixed;
        bottom: 20px;
        left: 20px;
        z-index: 9999;
    }
  </style>
{% if messages %}
{% for msg in messages%}
  <div {%if msg.tags %} id="myAlert" class="alert alert-{{msg.tags}} custom-alert" role="alert" {% endif%}>
    {{ msg }} 
  </div>

  <script>
    // بعد از یک ثانیه پیام حذف می‌شود
    setTimeout(function() {
      const alertBox = document.getElementById("myAlert");
      if (alertBox) {
        alertBox.remove();
      }
    }, 1500);
  </script>

{% endfor %}

{% endif %}

templates/navbar.html
{% load static %}
<header class="p-3 text-bg-dark sticky-top">
  <div class="container-fluid">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-between">

      <ul class="nav col-12 col-lg-auto ms-lg-auto mb-2 justify-content-start mb-md-0">
        <li><a href= "{% url 'home:home'%}" class="nav-link px-2 text-white">فروشگاه</a></li>
        <div class="vr"></div>
        <li><a href="{% url 'home:product' %}" class="nav-link px-2 text-white">محصولات</a></li>
        <div class="vr"></div>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            گروه محصولات
          </a>
          <ul class="dropdown-menu">

            <li><a class="dropdown-item" href="#">Action</a></li>
          </ul>
        </li>
        <div class="vr"></div>
        <li><a href="#" class="nav-link px-2 text-white">سبد خرید</a></li>
        <div class="vr"></div>
        <li><a href="#" class="nav-link px-2 text-white">گاری تصاویر</a></li>
        <div class="vr"></div>
        <li><a href="#" class="nav-link px-2 text-white">درباره ما</a></li>
      </ul>

      <div class="text-start">
      <button type="button" class="btn position-relative">
        <img src ="{% static 'icons/notifications.svg' %}" title="اعلان ها"> 
      <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
          99+
      <span class="visually-hidden">unread messages</span>
        </span>
      </button>
      
        {% if user.is_authenticated %}
        
                {% if user.is_staff or user.is_superuser %}
                <a type="button" class="btn" href= "/admin/"><img src ="{% static 'icons/admin_panel_settings.svg' %}" title="پنل ادمین"></a>
                {% endif %}
        <a type="button" class="btn" href= "{% url 'accounts:user_profile' %}" ><img src ="{% static 'icons/account.svg' %}" title="حساب کاربری"> </a>
        <a type="button" class="btn" href= "{% url 'accounts:user_logout' %}" > <img src ="{% static 'icons/logout.svg' %}" title="خروج از حساب"></a>

        {% else %}
        <a type="button" class="btn btn-warning" href= "{% url 'accounts:user_register'%}">ثبت نام</a>
        <a type="button" class="btn btn-success" href= "{% url 'accounts:user_login'%}">ورود</a>
        {% endif %}
      </div>
    </div>
  </div>
</header>

templates/sidebar.html
{% load static %}
    <div class="sidebar fixed-top">
        <div class="sidebar-header">
            <div class="icon">B</div>
            <div class="sidebar-title">پنل کاربری</div>
        </div>

        <!-- منو با آیکون -->
        <div class="menu-item" onclick="toggleMenu(this)">
            <div class="d-flex align-items-center">
                
                <img src="{% static 'icons/reports.svg' %}" class="menu-icon" alt="گزارشات">
                حساب کاربری
            </div>
            <span class="arrow">></span>
        </div>
        <div class="submenu">
            <div class="submenu-item"><a class="submenu-item" href="{% url 'accounts:user_profile' %}">اطلاعات حساب</a></div>
            <div class="submenu-item"><a class="submenu-item" href="{% url 'accounts:user_addresses' %}">آدرس ها</a><br></div>
            <div class="submenu-item"><a class="submenu-item" href="{% url 'accounts:user_changepassowrd' %}">تغییر رمز</a></div>
        </div>
        <div class="menu-item" onclick="toggleMenu(this)">
            <div class="d-flex align-items-center">
                
                <img src="{% static 'icons/reports.svg' %}" class="menu-icon" alt="گزارشات">
                گزارش ها
            </div>
            <span class="arrow">></span>
        </div>
        <div class="submenu">
            <div class="submenu-item">مرور کلی</div>
            <div class="submenu-item">آمار روزانه</div>
        </div>

        <div class="menu-item" onclick="toggleMenu(this)">
            <div class="d-flex align-items-center">
                <img src="{% static 'icons/users.svg' %}" class="menu-icon" alt="کاربران">
                کاربران
            </div>
            <span class="arrow">></span>
        </div>
        <div class="submenu">
            <div class="submenu-item">مرور کلی</div>
            <div class="submenu-item">آمار روزانه</div>
        </div>

        <div class="menu-item" onclick="toggleMenu(this)">
            <div class="d-flex align-items-center">
                <img src="{% static 'icons/orders.svg' %}" class="menu-icon" alt="سفارشات">
                سفارشات
            </div>
            <span class="arrow">></span>
        </div>
        <div class="submenu">
            <div class="submenu-item">لیست سفارشات</div>
            <div class="submenu-item">ثبت سفارش جدید</div>
        </div>

        <div class="menu-item" onclick="toggleMenu(this)">
            <div class="d-flex align-items-center">
                <img src="{% static 'icons/settings.svg' %}" class="menu-icon" >
                تنظیمات
            </div>
            <span class="arrow">></span>
        </div>
        <div class="submenu">
            <div class="submenu-item">لیست سفارشات</div>
            <div class="submenu-item">ثبت سفارش جدید</div>
        </div>
    </div>



    <script>
        function toggleMenu(item) {
            document.querySelectorAll('.menu-item').forEach(el => {
                if (el !== item) el.classList.remove('active');
            });
            item.classList.toggle('active');
        }
    </script>